protected/models/Timer.php
<?php

/**
 * @property integer $id
 * @property integer $expires
 * @property string $caption
 * @property string $message
 * @property User $created_by
 * @property string $created_at
 * @property integer $viewcount
 * @property string $cover_url
 * @property boolean $is_comments
 * @property string $cover
 * @property integer $privacy
 * @property integer $watchcount
 * @property string $local_alias
 * @property string $global_alias
 */

class Timer extends Model
{
  public $utcoffset;
  public $expires_value;
  public $email;

  const THUMBNAIL = true;
  
  const PRIVACY_ALL       = 0;
  const PRIVACY_PROFILE   = 100;
  const PRIVACY_LINK      = 200;
  const PRIVACY_ONLYME    = 255;
  
  private static $_hashids = null;
  private $_coverTmp;
  
  /************************************************** PUBLIC STATIC **************************************************/
  
  public static function decodeHash($hash)
  {
    $ret = self::_hashids()->decrypt($hash);
    return isset($ret[0]) ? $ret[0] : null;
  }
  
  public static function encodeHash($id)
  {
    return  self::_hashids()->encrypt((integer) $id);
  }
  
  public static function model($className=__CLASS__)
  {
    return parent::model($className);
  }
  
  public static function retrieve($id)
	{
  	return Timer::model()->findByPk($id);
	}
	
	public static function retrieveByHash($hash)
	{
  	return self::model()->findByPk(self::decodeHash($hash));
	}
	
	public static function retrieveByIdentifier($timerIdentifier)
	{
	  $parsedIdentifier = self::parseIdentifier($timerIdentifier);
	  if(isset($parsedIdentifier['hash'])) // by hash
	    return self::retrieveByHash($parsedIdentifier['hash']);
	  elseif(isset($parsedIdentifier['alias']))
	  {
  	  if(in_array($parsedIdentifier['alias'], Yii::app()->params['stopnicks']))
  	    return false;
  	  if(isset($parsedIdentifier['userIdentifier'])) // by local_alias
  	  {
    	  $user = User::retrieveByIdentifier($userIdentifier);
    	  if(!$user)
    	    return false;
      	$timer = Timer::model()->findByAttributes(array('created_by' => $user->getPrimaryKey(), 'local_alias' => $parsedIdentifier['alias']));
      	if(!$timer)
      	  return false;
      	 $timer->author = $user;
        return $timer;
  	  }
  	  else // by global_alias
        return Timer::model()->findByAttributes(array('global_alias' => $parsedIdentifier['alias']));
	  }
	  else
	    throw new TimerzInternalException('Unexpected situation in retrieveByIdentifier: timerIdentifier = ['.$timerIdentifier.'] parsedIdentifier = ' . print_r($parsedIdentifier, true));
    
	}
	
	/**
	 * @return Timer
	 */
	public static function retrieveForHomepage()
	{
  	return self::retrieve(self::getIdForHomepage());
	}
	
	/**
	 * Ротирует таймер для главной страницы и возвращает его id
	 * Таймер должен удовлетворять условиям:
	 * - иметь обложку
	 * - дата завершения больше чем через час
	 * - privacy <= PRIVACY_ALL
	 *
	 * @return integer
	 */
	public static function getIdForHomepage($rotate = false)
	{
	  $timerId = Yii::app()->cache->get('homepage_timer_id');
    if($timerId === false || $rotate)
    {
      $timerId = Timer::model()->dbConnection->createCommand('SELECT id FROM timer WHERE expires > UNIX_TIMESTAMP() + 3600 AND cover IS NOT NULL AND privacy = 0 ORDER BY RAND() LIMIT 1')->queryScalar();
      Yii::app()->cache->set('homepage_timer_id', $timerId, 3600);
    }
  	return $timerId;
	}
	
	public static function getPrivacyLabel($privacy, $contextMe = true)
	{
  	$options = self::getPrivacyOptions($contextMe);
  	if(!isset($options[$privacy]))
  	  throw new TimerzInternalException('Privacy not defined: ['.$privacy.']');
  	return $options[$privacy];
	}
	
	public static function getPrivacyOptions($contextMe = true)
	{
  	return array(
  	  Timer::PRIVACY_ALL     => Yii::t('timer', 'Access for all'),
  	  Timer::PRIVACY_PROFILE => $contextMe ? Yii::t('timer', 'Access from my page') : Yii::t('Access from user page'),
  	  Timer::PRIVACY_LINK    => $contextMe ? Yii::t('timer', 'Access whom I will give link') : Yii::t('timer', 'Access only by link'),
  	  Timer::PRIVACY_ONLYME  => Yii::t('timer', 'Access only for me'),
  	);
	}
	
	public static function getPrivacyIdentifier($privacy)
	{
  	switch($privacy)
  	{
    	case Timer::PRIVACY_ALL:      return 'all';
    	case Timer::PRIVACY_PROFILE:  return 'profile';
    	case Timer::PRIVACY_LINK:     return 'link';
    	case Timer::PRIVACY_ONLYME:   return 'onlyme';
    	default:
    	  return 'undefined';
  	}
	}
	
	public static function identifier($id, $alias = null, $userIdentifier = null)
  {
    if($alias)
    {
      if($userIdentifier)
        return $userIdentifier.'/'.$alias;
      else
        return $alias;
    }
    else
      return self::encodeHash($id);
  }
  
  public static function url($timerIdentifier, $action = 'show', $params = null, $absolute = false)
	{
	  if(is_array($action))
	  {
  	  $params = $action;
  	  $action = 'show';
	  }
	  elseif(is_bool($action))
	  {
  	  $absolute = $action;
  	  $action = 'show';
	  }
    if(is_null($params))
      $params = array();
    if(!is_array($params))
      $absolute = $params;
    $parsedIdentifier = self::parseIdentifier($timerIdentifier);
    $params['timerIdentifier'] = isset($parsedIdentifier['alias']) ? $parsedIdentifier['alias'] : $parsedIdentifier['hash'];
    if(isset($parsedIdentifier['userIdentifier']))
      $params['userIdentifier'] = $parsedIdentifier['userIdentifier'];
    return $absolute ? Yii::app()->createAbsoluteUrl('timer/'.$action, $params) : Yii::app()->createUrl('timer/'.$action, $params);
	}
	
	public static function parseIdentifier($timerIdentifier)
	{
	  $result = array();
  	$explode = explode('/', $timerIdentifier);
  	$result[is_null(self::decodeHash($explode[0])) ? 'alias' : 'hash'] = $explode[count($explode)-1];
  	if(count($explode) > 1)
  	  $result['userIdentifier'] = $explode[0];
  	 return $result;
	}
  
  /************************************************** PUBLIC **************************************************/
  
	public function tableName()
	{
		return 'timer';
	}
  
	public function rules()
	{
		$rules = array(
		  array('utcoffset' , 'numerical', 'min' => -840, 'max' => 840, 'allowEmpty' => false),
		  array('caption', 'required'),
			array('caption' , 'length', 'max' => 300, 'allowEmpty' => false),
			array('message' , 'length', 'max' => 1000, 'allowEmpty' => true),
			array('description' , 'length', 'max' => 1000, 'allowEmpty' => true),
			array('cover_url' , 'length', 'max' => 300, 'allowEmpty' => true),
			array('is_comments' , 'boolean'),
			array('privacy', 'in', 'range' => array_keys(self::getPrivacyOptions())),
			array('expires', 'expiresValidation')
		);
		if(Yii::app()->user->isGuest)
		{
  		$rules[] = array('email' , 'length', 'max' => 45, 'allowEmpty' => false);
  		$rules[] = array('email' , 'email');
		}
		return $rules;
	}
	
	public function getExpiresValue()
	{
  	if($this->expires_value)
      return $this->expires_value;
    elseif($this->getAttribute('expires'))
      return date('d.m.Y H:i:s', $this->getAttribute('expires'));
    else return null;
	}
	
	public function expiresValidation($attribute, $params)
  {
    $utcOffsetInSeconds = -$this->utcoffset*60;
    $this->expires_value = $this->getAttribute('expires');
    if(!$this->expires_value)
      return $this->addError('expires', Yii::t('timer', 'Timer must have expiration date'));
    $expires = Utility::strtotime($this->expires_value, $utcOffsetInSeconds);
    if(!$expires)
      return $this->addError('expires', Yii::t('timer', 'Unrecognized format'));
    if($expires < time())
      return $this->addError('expires', Yii::t('timer', 'Expiration date should be in the future'));
    $this->setAttribute('expires', $expires);
  }
	
	public function attributeLabels()
	{
		return array(
		  'caption' => Yii::t('timer', 'Caption'),
		  'message' => Yii::t('timer', 'Message'),
		  'cover_url' => 'URL картинки',
		  'cover' => 'Фоновая картинка',
		  'expires' => Yii::t('timer', 'Expiration'),
		  'is_comments' => Yii::t('timer', 'Comments'),
		  'description' => Yii::t('timer', 'Description'),
		  'email' => Yii::t('timer', 'Your email'),
		  'utcoffset' => 'UTC offset',
		  'privacy' => Yii::t('timer', 'Privacy'),
		);
	}
	
	public function relations()
	{
  	return array(
  	  'user' => array(self::BELONGS_TO, 'User', 'created_by'),
  	);
	}
	
	public function getLink($action = 'show', $params = null, $absolute = false)
	{
	  return self::url($this->getIdentifier(), $action, $params, $absolute);
	}
	
	public function getHash()
	{
  	return self::encodeHash($this->getPrimaryKey());
	}
	
	public function hasAlias()
	{
  	return $this->getAttribute('global_alias') || $this->getAttribute('local_alias');
	}
	
	public function isExpired()
	{
  	return $this->getAttribute('expires') <= time();
	}
	
	public function hasCover()
	{
  	return (bool) $this->getAttribute('cover');
	}
	
	public function setCover($cover)
	{
	  $this->_coverTmp = CoverTmp::retrieve($cover);
	}
	
	public function deleteCover()
	{
	  $this->_coverTmp = 'delete';
	}
	
	public function getCoverPath($thumbnail = false)
	{
  	return Yii::app()->params['coverPath'].DIRECTORY_SEPARATOR.User::encodeHash($this->getAttribute('created_by')).DIRECTORY_SEPARATOR.$this->getAttribute('cover').($thumbnail ? '_t' : '').'.jpg';
	}
	
	public function getCoverUrl($thumbnail = false)
	{
  	return Yii::app()->params['coverBaseUrl'].'/' . User::encodeHash($this->getAttribute('created_by')) . '/' . $this->getAttribute('cover') . ($thumbnail ? '_t' : '').'.jpg';
	}
	
	public function getMessage()
	{
  	$message = $this->getAttribute('message');
  	return $message ? $message : Yii::t('timer', 'Timer ended');
	}
	
	public function isComments()
	{
  	return $this->getAttribute('is_comments');
	}
	
	public function isMy()
	{
  	return !Yii::app()->user->isGuest && $this->getAttribute('created_by') == Yii::app()->user->getId();
	}
	
	public function getAuthor()
	{

protected/controllers/MainController.php
<?php

class MainController extends Controller
{
  
  public function actionHomepage()
  {
    $timer = Timer::retrieveForHomepage();
    if($timer)
      $timer->incrementViewcount();
    $this->page = 'homepage';
    $this->pageTitle = Yii::t('app', 'Timerz - countdown timers');
    $this->hasPageTitlePostfix = false;
    $this->render('homepage', array('timer' => $timer));
  }
  
  /**
	 * This is the action to handle external exceptions.
	 */
  public function actionError()
  {
    if($error = Yii::app()->errorHandler->error)
    {
      $this->layout = 'narrowWithPageHeader';
      switch($error['code'])
      {
        case 403:
          $this->pageTitle = Yii::t('app', 'Access denied');
          $view = 'error403';
          break;
        case 404:
          $this->pageTitle = Yii::t('app', 'Page not found');
          $view = 'error404';
          break;
        default:
          $this->pageTitle = Yii::t('app', 'Error');
          $view = 'error500';
      }
      $this->render($view, array('error' => $error));
    }
  }
}

protected/controllers/TimerController.php
<?php

class TimerController extends Controller
{
  
  public function actionShow()
  {
    $timer = $this->_getTimer();
    if(!($timer->isMy() || $timer->privacyIsUnder(Timer::PRIVACY_LINK)))
      throw new CHttpException(403);
    $this->page = 'timerpage';
    $this->pageTitle = $timer->getAttribute('caption') ? $timer->getAttribute('caption') : $timer->getIdentifier();
    $timer->incrementViewcount();
    $params = array('maintimer', 'about', 'comments', 'description', 'centered', 'dynamic-cover', 'undertimer', 'watch', 'dynamic-bottom-border');
  	$this->render('show', array('timer' => $timer, 'params' => $params));
  }
  
  public function actionList($type)
  {
    $this->layout = 'narrowColWithPageHeader';
    
    $query = Timer::model();
    
    switch($type)
    {
      case 'last':
        $this->pageTitle = Yii::t('timer', 'Last added');
        $query->last();
        break;
      case 'soon':
        $this->pageTitle = Yii::t('timer', 'Coming soon');
        $query->soon();
        break;
      case 'ended':
        $this->pageTitle = Yii::t('timer', 'Recently ended');
        $query->ended();
        break;
      case 'popular':
        $this->pageTitle = Yii::t('timer', 'Popular timers');
        $query->popular();
        break;
      default:
        throw new CHttpException(404);
    }
    
    $query->privacyUnder(Timer::PRIVACY_ALL);
      
    if($type != 'ended')
      $query->notEnded();
    
    $this->render('list', array('timersCriteria' => $query->getDbCriteria()));
  }
  
  public function actionGetMessage($id)
  {
    $timer = Timer::retrieve($id);
    if(!$timer)
      throw new CHttpException(404);
    if($timer->isExpired())
      echo CHtml::encode($timer->getMessage());
    else
      echo "Timer not ended";
    Yii::app()->end();
  }
  
  public function actionStrtotime($time, $utcoffset = 0)
  {
    $utcOffsetInSeconds = -$utcoffset*60;
    echo Utility::strtotime($time, $utcOffsetInSeconds);
    Yii::app()->end();
  }
  
  public function actionWatching($action)
  {
    if(Yii::app()->user->isGuest)
    {
      $request = Yii::app()->getRequest();
      if(!$request->getIsAjaxRequest())
        Yii::app()->user->setReturnUrl($request->getUrl());
      $this->redirect(array('security/signup'));
    }
    $timer = $this->_getTimer();
    switch($action)
    {
      case 'watching':
        $timer->watch(Yii::app()->user->getId());
        break;
      case 'stopWatching':
        $timer->stopWatching(Yii::app()->user->getId());
        break;
      default:
        throw new CHttpException(404, 'action must be watching or stopWatching');
    }
    $this->redirect($timer->getLink());
  }
  
  public function actionEdit()
  {
    $timer = $this->_getTimer();
    if(Yii::app()->user->isGuest)
      Yii::app()->user->loginRequired();
    elseif(Yii::app()->user->id != $timer->getAttribute('created_by'))
      throw new CHttpException(403);
    $timer->setScenario('update');
    $this->pageTitle = Yii::t('timer', 'Edit timer');
    $this->_createOrEdit($timer);
  }
  
  public function actionCreate()
  {
    $this->pageTitle = Yii::t('timer', 'Create timer');
    $timer = new Timer('insert');
    $this->_createOrEdit($timer);
  }
  
  public function actionUploadCover()
  {
    $response = array('coverTmpHash' => '', 'error' => 0, 'errorMessage' => null);
    if(is_uploaded_file($_FILES['timer']['tmp_name']['cover']))
    {
      if(filesize($_FILES['timer']['tmp_name']['cover']) > Yii::app()->params['maxUploadCoverSize'])
      {
        $response['error'] = 3;
        $response['errorMessage'] = Yii::t('app', 'Max file size: {size}mb', array('{size}' => floor(Yii::app()->params['maxUploadCoverSize'] / 1048576)));
      }
      else
      {
        try
        {
          $coverTmp = CoverTmp::createFromFile($_FILES['timer']['tmp_name']['cover']);
          $response['coverTmpHash'] = $coverTmp->getHash();
          $response['coverUrl'] = $coverTmp->getUrl();
        }
        catch(Exception $e)
        {
          // TODO: log this error
          $response['error'] = 1;
          $response['errorMessage'] = Yii::t('app', 'Upload error, try another');
        }
      }
    }
    else
    {
      // TODO: log this error
      $response['error'] = 2;
      $response['errorMessage'] = Yii::t('app', 'Upload error, try another');
    }
    echo CJavaScript::jsonEncode($response);
    Yii::app()->end();
  }
  
  public function actionWatchers()
  {
    $this->layout = 'narrow';
    $timer = $this->_getTimer();
    $watchers = $timer->getWatchers();
    $this->render('watchers', array('timer' => $timer ,'users' => $watchers));
  }
  
  /************************************************** PRIVATE **************************************************/
  
  private function _createOrEdit($timer)
  {
    $this->layout = 'narrow';
    if(isset($_POST['timer']))
    {
      if(!isset($_POST['timer']['honeypot']) || $_POST['timer']['honeypot'])
      {
        echo "You are bot";
        throw new TimerzWarningException("You are bot");
        Yii::app()->end();
      }
      
      if(isset($_POST['timer']['honeypot']))
        unset($_POST['timer']['honeypot']);
      
      if(!isset($_POST['timer']['is_comments']))
        $_POST['timer']['is_comments'] = 0;
      
      if(isset($_POST['timer']['cover']))
      {
        if($_POST['timer']['cover'] == 'delete')
          $timer->deleteCover();
        else
          $timer->setCover($_POST['timer']['cover']);
        unset($_POST['timer']['cover']);
      }
      $timer->attributes = $_POST['timer'];
      $result = $timer->save();
      if(Yii::app()->request->isAjaxRequest)
      {
        $response = array(
          'result' => $result ? 'ok' : 'fail',
          'errors' => $timer->getErrors(),
          'url' => $result ? $timer->getLink() : null,
        );
        echo CJavaScript::jsonEncode($response);
        Yii::app()->end();
      }
      else
      {
        if($result)
          $this->redirect($timer->getLink());
      }
    }
    $this->render('create', array('timer' => $timer));
  }
  
  /**
   * @return Timer
   */
  private function _getTimer()
  {
    $params = $this->getActionParams();
    if(!isset($params['timerIdentifier']))
      throw new TimerzInternalException('timerIdentifier must be setted before calling TimerController::_getTimer');
    $timerIdentifier = $params['timerIdentifier'];
    if(isset($params['userIdentifier']))
      $timerIdentifier = $params['userIdentifier'] . '/' . $timerIdentifier;
    $timer = Timer::retrieveByIdentifier($timerIdentifier);
    if($timer->hasAlias() && !is_null(Timer::decodeHash($timerIdentifier)))
      $this->redirect($timer->getLink(), true, 301);
    return $timer;
  }
  
}

protected/views/timer/_form.php
<form class="timer-form <?php if($timer->isNewRecord) echo 'is_new'?> <?php if($timer->hasCover()) echo 'has_cover'?>" action="<?php echo $timer->isNewRecord ? $this->createUrl('timer/create') : $timer->getLink('edit') ?>" method="post" enctype="multipart/form-data">

  <input type="hidden" id="timer_utcoffset" class="value" name="timer[utcoffset]">
  <input type="hidden" class="value" name="timer[honeypot]">
  <input type="hidden" id="timer_cover" class="value" name="timer[cover]">
  <script>document.getElementById("timer_utcoffset").value = (new Date()).getTimezoneOffset();</script>
  
  <div class="form-group required <?php if($timer->hasErrors('caption')) echo 'has-error'; elseif($timer->getAttribute('caption')) echo 'has-success';?>">
    <label class="control-label" for="timer_caption"><?php echo $timer->getAttributeLabel('caption')?></label>
    <input type="text"  name="timer[caption]" id="timer_caption" class="form-control value" placeholder="<?php echo Yii::t('timer', 'ex: before my birthday left')?>" value="<?php echo CHtml::encode($timer->getAttribute('caption'))?>">
    <p class="error help-block"><?php echo $timer->getError('caption')?></p>
  </div>
  
  <div class="form-group required <?php if($timer->hasErrors('expires')) echo 'has-error'; elseif($timer->getExpiresValue()) echo 'has-success';?>">
    <label class="control-label" for="timer_expires"><?php echo $timer->getAttributeLabel('expires')?></label>
    <input type="text" name="timer[expires]" id="timer_expires" class="form-control value" placeholder="<?php echo Yii::t('timer', 'ex: {datetime} or {time}', array('{datetime}' => '21.10.2015 16:29', '{time}' => '23:59'))?>" value="<?php echo CHtml::encode($timer->getExpiresValue())?>" data-timestamp="<?php echo $timer->getAttribute('expires')?>">
    <p class="error help-block"><?php echo $timer->getError('expires')?></p>
  </div>
  
  <?php $this->beginClip('message') ?>
    <div class="form-group <?php if($timer->hasErrors('message')) echo ' has-error'; elseif($timer->getAttribute('message')) echo 'has-success'?>">
      <label class="control-label" for="timer_message"><?php echo $timer->getAttributeLabel('message')?></label>
      <textarea  name="timer[message]" id="timer_message" class="form-control value" rows="3" placeholder="<?php echo Yii::t('timer', 'will show after timer expiration')?>"><?php echo $timer->getAttribute('message')?></textarea>
      <p class="error help-block"><?php echo $timer->getError('message')?></p>
    </div>
  <?php $this->endClip() ?>
  
  <?php if(Yii::app()->user->isGuest):?>
    <div class="form-group required <?php if($timer->hasErrors('email')) echo 'has-error'; elseif($timer->email) echo 'has-success';?>">
      <label class="control-label" for="timer_email"><?php echo $timer->getAttributeLabel('email')?></label>
      <input type="text" name="timer[email]" id="timer_email" class="form-control value" value="<?php echo CHtml::encode($timer->email)?>" placeholder="<?php echo Yii::t('timer', 'where to send the link to control')?>">
      <p class="error help-block"><?php echo $timer->getError('email')?></p>
    </div>
  <?php else: ?>
    <?php echo $this->clips['message'] ?>
  <?php endif ?>
  
  <div class="form-group additional-switch">
    <a href="#" class="additional-show"><span class="glyphicon glyphicon-chevron-down"></span> <?php echo Yii::t('timer', 'Additional attributes')?></a>
    <a href="#" class="additional-hide"><span class="glyphicon glyphicon-chevron-up"></span> <?php echo Yii::t('timer', 'Additional attributes')?></a>
  </div>
  
  
  <div class="additional">
    
    <?php if(Yii::app()->user->isGuest) echo $this->clips['message'] ?>
    
    <?php if(isset($showTimer) && $showTimer):?>
    <div class="timers example">
      <?php echo $this->renderPartial('//timer/show', array('timer' => $timer, 'params' => array('maintimer')), true)?>
    </div>
    <?php endif ?>
    
    <div class="form-group cover">
      
      
        <span class="btn btn-primary fileinput-button">
          <span class="choose"><?php echo Yii::t('timer', 'Upload picture')?></span>
          <span class="change"><?php echo Yii::t('timer', 'Edit picture')?></span>
          <input type="file" name="timer[cover]" id="timer_cover_upload" data-url="<?php echo $this->createUrl('timer/uploadCover')?>">
        </span>
        <button type="button" class="btn btn-danger delete">
          <i class="glyphicon glyphicon-trash"></i>
          <span><?php echo Yii::t('app', 'Delete')?></span>
        </button>
      
      <div class="progress">
        <div class="progress-bar" role="progressbar"></div>
      </div>
    </div>

    <div class="form-group <?php if($timer->hasErrors('description')) echo ' has-error'; elseif($timer->getAttribute('description')) echo 'has-success'?>">
      <label class="control-label" for="timer_description"><?php echo $timer->getAttributeLabel('description')?></label>
      <textarea  name="timer[description]" id="timer_description" class="form-control value" rows="3" placeholder="<?php echo Yii::t('timer', 'displayed under timer')?>"><?php echo $timer->getAttribute('description')?></textarea>
      <p class="error help-block"><?php echo $timer->getError('description')?></p>
    </div>
    
    <div class="form-group">

      <label class="control-label" for="timer_privacy"><?php echo $timer->getAttributeLabel('privacy')?></label>
      <select class="value" id="timer_privacy" name="timer[privacy]">
        <?php foreach(Timer::getPrivacyOptions() AS $privacyValue => $privacyLabel):?>
          <option<?php if($timer->privacyIs($privacyValue)):?> selected<?php endif ?> value="<?php echo $privacyValue ?>"><?php echo $privacyLabel?></option>
        <?php endforeach ?>
      </select>
    </div>
    
    <div class="checkbox">
      <label>
        <input type="checkbox" name="timer[is_comments]" class="value" value="1" <?php if($timer->isComments()):?>checked="checked"<?php endif ?>> <?php echo $timer->getAttributeLabel('is_comments')?> <span class="text-muted"><?php echo Yii::t('timer', 'on timer page')?></span>
      </label>
    </div>
    
  </div>
  
  <div class="form-group text-center buttons">
    <button type="submit" class="btn btn-success btn-lg" data-loading-text="Загрузка..."><?php echo $timer->isNewRecord ? Yii::t('timer', 'Create timer') : Yii::t('app', 'Save') ?></button>
    <?php if(isset($showCancel) && $showCancel):?>
      <a class="btn btn-lg btn-warning" href="<?php echo $this->createUrl($timer->isNewRecord ? 'main/homepage' : $timer->getLink())?>"><?php echo Yii::t('app', 'Cancel')?></a>
    <?php endif ?>
  </div>
  
</form>

protected/views/timer/create.php
<div class="page-header">
  <h1><?php echo CHtml::encode($this->pageTitle) ?></h1>
  
  <p class="lead">
    <?php if($timer->isNewRecord) echo Yii::t('timer', 'Create countdown timer to your event and share it with family, friends or whole world!')?>
  </p>
</div>

<?php echo $this->renderPartial('_form', array('timer' => $timer, 'showTimer' => true, 'showCancel' => true), true)?>

protected/views/timer/list.php
<?php

$this->widget('application.widgets.TimersListWidget', array('criteria' => $timersCriteria, 'params' => array('about', 'timerlink')));

protected/views/timer/watchers.php
<div class="page-header">
  <h1><?php echo Yii::t('timer', 'Watchers of timer')?> <a href="<?php echo $timer->getLink() ?>"><?php echo substr($timer->getLink(), 1)?></a></h1>
</div>

<div class="watchers">
  <?php if(count($users) == 0) echo Yii::t('timer', 'no watchers') ?>
  
  <?php foreach($users AS $user):?>
    <span class="watcher"><a href="<?php echo $user->getLink()?>"><?php echo $user->getIdentifier()?></a></span>
  <?php endforeach ?>
</div>