protected/controllers/SecurityController.php
<?php

class SecurityController extends Controller
{
  
  public function filters()
  {
    return array(
      'redirectChecker - signout, auth, endpoint, restorePassword',
    );
  }
  
  public function filterRedirectChecker($filterChain)
  {
    if(!Yii::app()->user->isGuest)
      $this->redirect(Yii::app()->user->getLink());
    else
      $filterChain->run();
  }
  
  public function actionSignin()
  {
    $this->pageTitle = Yii::t('app', 'Sign in');
    $model = new SigninForm;
    if(isset($_POST['singin']))
		{
		  $model->attributes = $_POST['singin'];
			if($model->validate())
				$this->redirect(Yii::app()->user->returnUrl == '/' ? Yii::app()->user->getLink() : Yii::app()->user->returnUrl);
		}
  	$this->render('signin', array('model' => $model));
  }
  
  public function actionSignup()
  {
    $error = false;
    $email = null;
    if(isset($_POST['signup']) && isset($_POST['signup']['email']))
    {
      $email = trim($_POST['signup']['email']);
      $validator = new CEmailValidator;
      if($validator->validateValue($email))
      {
        if($user = User::createByEmail($email))
          $this->redirect(Yii::app()->user->returnUrl);
        else
          $error = Yii::t('security', 'User with this email is already registered');;
      }
      else
        $error = Yii::t('security', 'Invalid email format');
    }
    $this->pageTitle = Yii::t('app', 'Sign up');
  	$this->render('signup', array('error' => $error, 'email' => $email));
  }
  
  public function actionSignout()
	{
  	Yii::app()->user->logout();
  	$this->redirect(array('main/homepage'));
	}
	
	public function actionRestorePassword($user = null, $key = null)
	{
	  $this->layout = 'narrowWithPageHeader';
	  $this->pageTitle = Yii::t('security', 'Restore password');
	  if(!is_null($user) && !is_null($key))
	  {
  	  $user = User::retrieveByHash($user);
  	  if($user && $user->restorePasswordValid($key))
      {
        $user->resetPassword();
        if(Yii::app()->user->isGuest || Yii::app()->user->getId() != $user->getPrimaryKey())
          Yii::app()->user->loginAsUser($user);
        $this->redirect(array('account/changePassword'));
      }
      else
        $this->render('restorePasswordInvalid');
	  }
	  else
	  {
  	  $error = null;
  	  $login = null;
  	  if(isset($_POST['restorePassword']['login']))
  		{
  		  $login = trim($_POST['restorePassword']['login']);
  		  if(!$login)
  		    $error =  Yii::t('security', 'Enter your email or nickname');
  			elseif($user = User::retrieveByLogin($login))
  			{
  			  if($user->setRestorePasswordHash())
    			  $this->redirect(array('security/restorePasswordSended'));
          else
    			  $error = Yii::t('security', 'Unable to send link to password restore');
  			}
        else
          $error = Yii::t('security', 'User not found');
  		}
    	$this->render('restorePassword', array('error' => $error, 'login' => $login));
    }
	}
	
	public function actionRestorePasswordSended()
	{
	  $this->layout = 'narrowWithPageHeader';
	  $this->pageTitle = Yii::t('security', 'Restore password');
	  $this->render('restorePassword', array('sended' => 'yes'));
	}
	
	public function actionEndpoint()
	{
  	Hybrid_Endpoint::process();
	}
	
	public function actionAuth($provider)
	{
  	//
	}
}

protected/controllers/TimerController.php
<?php

class TimerController extends Controller
{
  
  public function actionShow()
  {
    $timer = $this->_getTimer();
    if(!($timer->isMy() || $timer->privacyIsUnder(Timer::PRIVACY_LINK)))
      throw new CHttpException(403);
    $this->page = 'timerpage';
    $this->pageTitle = $timer->getAttribute('caption') ? $timer->getAttribute('caption') : $timer->getIdentifier();
    $timer->incrementViewcount();
    $params = array('maintimer', 'about', 'comments', 'description', 'centered', 'dynamic-cover', 'undertimer', 'watch', 'dynamic-bottom-border');
  	$this->render('show', array('timer' => $timer, 'params' => $params));
  }
  
  public function actionList($type)
  {
    $this->layout = 'narrowColWithPageHeader';
    
    $query = Timer::model();
    
    switch($type)
    {
      case 'last':
        $this->pageTitle = Yii::t('timer', 'Last added');
        $query->last();
        break;
      case 'soon':
        $this->pageTitle = Yii::t('timer', 'Coming soon');
        $query->soon();
        break;
      case 'ended':
        $this->pageTitle = Yii::t('timer', 'Recently ended');
        $query->ended();
        break;
      case 'popular':
        $this->pageTitle = Yii::t('timer', 'Popular timers');
        $query->popular();
        break;
      default:
        throw new CHttpException(404);
    }
    
    $query->privacyUnder(Timer::PRIVACY_ALL);
      
    if($type != 'ended')
      $query->notEnded();
    
    $this->render('list', array('timersCriteria' => $query->getDbCriteria()));
  }
  
  public function actionGetMessage($id)
  {
    $timer = Timer::retrieve($id);
    if(!$timer)
      throw new CHttpException(404);
    if($timer->isExpired())
      echo CHtml::encode($timer->getMessage());
    else
      echo "Timer not ended";
    Yii::app()->end();
  }
  
  public function actionStrtotime($time, $utcoffset = 0)
  {
    $utcOffsetInSeconds = -$utcoffset*60;
    echo Utility::strtotime($time, $utcOffsetInSeconds);
    Yii::app()->end();
  }
  
  public function actionWatching($action)
  {
    if(Yii::app()->user->isGuest)
    {
      $request = Yii::app()->getRequest();
      if(!$request->getIsAjaxRequest())
        Yii::app()->user->setReturnUrl($request->getUrl());
      $this->redirect(array('security/signup'));
    }
    $timer = $this->_getTimer();
    switch($action)
    {
      case 'watching':
        $timer->watch(Yii::app()->user->getId());
        break;
      case 'stopWatching':
        $timer->stopWatching(Yii::app()->user->getId());
        break;
      default:
        throw new CHttpException(404, 'action must be watching or stopWatching');
    }
    $this->redirect($timer->getLink());
  }
  
  public function actionEdit()
  {
    $timer = $this->_getTimer();
    if(Yii::app()->user->isGuest)
      Yii::app()->user->loginRequired();
    elseif(Yii::app()->user->id != $timer->getAttribute('created_by'))
      throw new CHttpException(403);
    $timer->setScenario('update');
    $this->pageTitle = Yii::t('timer', 'Edit timer');
    $this->_createOrEdit($timer);
  }
  
  public function actionCreate()
  {
    $this->pageTitle = Yii::t('timer', 'Create timer');
    $timer = new Timer('insert');
    $this->_createOrEdit($timer);
  }
  
  public function actionUploadCover()
  {
    $response = array('coverTmpHash' => '', 'error' => 0, 'errorMessage' => null);
    if(is_uploaded_file($_FILES['timer']['tmp_name']['cover']))
    {
      if(filesize($_FILES['timer']['tmp_name']['cover']) > Yii::app()->params['maxUploadCoverSize'])
      {
        $response['error'] = 3;
        $response['errorMessage'] = Yii::t('app', 'Max file size: {size}mb', array('{size}' => floor(Yii::app()->params['maxUploadCoverSize'] / 1048576)));
      }
      else
      {
        try
        {
          $coverTmp = CoverTmp::createFromFile($_FILES['timer']['tmp_name']['cover']);
          $response['coverTmpHash'] = $coverTmp->getHash();
          $response['coverUrl'] = $coverTmp->getUrl();
        }
        catch(Exception $e)
        {
          // TODO: log this error
          $response['error'] = 1;
          $response['errorMessage'] = Yii::t('app', 'Upload error, try another');
        }
      }
    }
    else
    {
      // TODO: log this error
      $response['error'] = 2;
      $response['errorMessage'] = Yii::t('app', 'Upload error, try another');
    }
    echo CJavaScript::jsonEncode($response);
    Yii::app()->end();
  }
  
  public function actionWatchers()
  {
    $this->layout = 'narrow';
    $timer = $this->_getTimer();
    $watchers = $timer->getWatchers();
    $this->render('watchers', array('timer' => $timer ,'users' => $watchers));
  }
  
  /************************************************** PRIVATE **************************************************/
  
  private function _createOrEdit($timer)
  {
    $this->layout = 'narrow';
    if(isset($_POST['timer']))
    {
      if(!isset($_POST['timer']['honeypot']) || $_POST['timer']['honeypot'])
      {
        echo "You are bot";
        throw new TimerzWarningException("You are bot");
        Yii::app()->end();
      }
      
      if(isset($_POST['timer']['honeypot']))
        unset($_POST['timer']['honeypot']);
      
      if(!isset($_POST['timer']['is_comments']))
        $_POST['timer']['is_comments'] = 0;
      
      if(isset($_POST['timer']['cover']))
      {
        if($_POST['timer']['cover'] == 'delete')
          $timer->deleteCover();
        else
          $timer->setCover($_POST['timer']['cover']);
        unset($_POST['timer']['cover']);
      }
      $timer->attributes = $_POST['timer'];
      $result = $timer->save();
      if(Yii::app()->request->isAjaxRequest)
      {
        $response = array(
          'result' => $result ? 'ok' : 'fail',
          'errors' => $timer->getErrors(),
          'url' => $result ? $timer->getLink() : null,
        );
        echo CJavaScript::jsonEncode($response);
        Yii::app()->end();
      }
      else
      {
        if($result)
          $this->redirect($timer->getLink());
      }
    }
    $this->render('create', array('timer' => $timer));
  }
  
  /**
   * @return Timer
   */
  private function _getTimer()
  {
    $params = $this->getActionParams();
    if(!isset($params['timerIdentifier']))
      throw new TimerzInternalException('timerIdentifier must be setted before calling TimerController::_getTimer');
    $timerIdentifier = $params['timerIdentifier'];
    if(isset($params['userIdentifier']))
      $timerIdentifier = $params['userIdentifier'] . '/' . $timerIdentifier;
    $timer = Timer::retrieveByIdentifier($timerIdentifier);
    if($timer->hasAlias() && !is_null(Timer::decodeHash($timerIdentifier)))
      $this->redirect($timer->getLink(), true, 301);
    return $timer;
  }
  
}

protected/views/layouts/email.php
<html>
<head>	
	<meta charset="utf-8">
	<title>Timerz</title>
	<style type="text/css">
	  body {font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:16px;line-height: 1.428571429em;padding:5px;}
	  html,input,textarea {-webkit-font-smoothing: antialiased !important;}
	  .logo {font-weight: bold;font-size: 1.7em;background-color: #428bca;color:#fff;text-decoration: none;padding:15px;display: block;float:left;margin-bottom: 15px;}
	   .text-muted {color: #666;}
	  .content {clear:both;}
	  h1, h2 {font-weight: normal;}
	</style>
</head>
<body>
  <div>
    <a class="logo" href="http://timerz.org">timer:z</a>
    <p class="content">
      <?php echo $content ?>
    </p>
  </div>
</body>
</html>

protected/views/layouts/main.php
<?php
$timersMenu = array(
  'popular' => Yii::t('timer', 'Popular'),
  'soon'    => Yii::t('timer', 'Soon'),
  'last'    => Yii::t('timer', 'Last'),
  'ended'   => Yii::t('timer', 'Ended'),
);
?>
<!DOCTYPE html>
<html>
<head>	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title><?php echo CHtml::encode($this->pageTitle) . ($this->hasPageTitlePostfix ? ' - Timerz' : '') ?></title>
	
	<?php Yii::app()->clientScript->registerPackage('css') ?>
	<?php Yii::app()->clientScript->registerPackage('js') ?>
	
  <!-- CSS adjustments for browsers with JavaScript disabled -->
  <noscript><link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/jquery.fileupload-ui-noscript.css"></noscript>

	
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/html5shiv.js"></script>
      <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/respond.min.js"></script>
    <![endif]-->

</head>
<body class="<?php if(!is_null($this->page)) echo $this->page?>">

<!-- Wrap all page content here -->
  <div id="wrap">
    <div id="dynamic-cover"></div>
    
    <div id="timerz-nav" class="compact">
      <div class="container">
        <a class="navbar-brand ticklogo" href="#">timer<span>:</span>z</a>
        <div class="account">
        <?php $this->beginClip('account') ?>
          <?php if(Yii::app()->user->isGuest):?>
            <a href="<?php echo $this->createUrl('security/signin')?>" <?php if($this->routeIs('security', 'signin')):?>class="active"<?php endif ?>><span class="glyphicon glyphicon-user"></span> <?php echo Yii::t('app', 'Sign in')?></a>
          <?php else: ?>
            <a href="<?php echo $this->createUrl('account/index')?>" <?php if($this->routeIs('account')):?>class="active"<?php endif ?>><span class="glyphicon glyphicon-cog"></span> <?php echo Yii::t('app', 'Settings')?></a>
          <?php endif ?>
        <?php $this->endClip() ?>
          <?php echo $this->clips['account'] ?>
        </div>
        <ul class="menu">
          <li class="compacted"><a href="/"<?php if($this->routeIs('main', 'homepage')):?> class="active"<?php endif ?>><span class="glyphicon glyphicon-home"></span> <?php echo Yii::t('timer', 'Home')?></a></li>
          <?php if(!Yii::app()->user->isGuest):?><li><a href="<?php echo User::url(User::identifier(Yii::app()->user->id, Yii::app()->user->name))?>"<?php if($this->routeIs('user', 'show', array('userIdentifier' => User::identifier(Yii::app()->user->id, Yii::app()->user->name)))):?> class="active"<?php endif ?>><span class="glyphicon glyphicon-time"></span> <?php echo Yii::t('timer', 'My timers')?></a></li><?php endif ?>
          <li><a href="<?php echo $this->createUrl('timer/create') ?>"<?php if($this->routeIs('timer', 'create')):?> class="active"<?php endif ?>><span class="glyphicon glyphicon-plus"></span> <?php echo Yii::t('timer', 'New timer')?></a></li>
          <?php foreach($timersMenu as $type => $name):?>
            <li><a href="<?php echo $this->createUrl('timer/list', array('type' => $type)) ?>"<?php if($this->routeIs('timer', 'list', array('type' => $type))):?> class="active"<?php endif ?>><?php echo $name?></a></li>
          <?php endforeach ?>
          <li class="account"><?php echo $this->clips['account'] ?></li>
        </ul>
        
      </div>
    </div>

    <!-- Begin page content -->
    
    <div id="content">
      <div class="container">
        <?php echo $content ?>
      </div>
    </div>
    
  </div>
  
  <div id="footer">
    <div class="container">
      <p class="text-muted credit"><span class="item">&copy; Timerz 2013</span> <?php if(YII_DEBUG || (isset($_GET['debug']) && $_GET['debug'] = '1')):?><span class="item"><?php echo sprintf('%.2fms %.2fmb', Yii::getLogger()->getExecutionTime()*1000, memory_get_peak_usage()/1048576)?></span><?php endif ?></p>
    </div>
  </div>
	
	<?php if(!YII_DEBUG):?>
	<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-44053205-1', 'timerz.org');
    ga('send', 'pageview');
  </script>
  <?php endif ?>
  
</body>
</html>

protected/views/layouts/narrow.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <?php echo $content ?>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/narrowColWithPageHeader.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="page-header">
      <h1><?php echo CHtml::encode($this->pageTitle) ?></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col">
    <?php echo $content ?>
  </div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/narrowWithPageHeader.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="page-header">
      <h1><?php echo CHtml::encode($this->pageTitle) ?></h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <?php echo $content ?>
  </div>
</div>
<?php $this->endContent(); ?>