protected/controllers/SecurityController.php
<?php

class SecurityController extends Controller
{
  
  public function filters()
  {
    return array(
      'redirectChecker - signout, auth, endpoint, restorePassword',
    );
  }
  
  public function filterRedirectChecker($filterChain)
  {
    if(!Yii::app()->user->isGuest)
      $this->redirect(Yii::app()->user->getLink());
    else
      $filterChain->run();
  }
  
  public function actionSignin()
  {
    $this->pageTitle = Yii::t('app', 'Sign in');
    $model = new SigninForm;
    if(isset($_POST['singin']))
		{
		  $model->attributes = $_POST['singin'];
			if($model->validate())
				$this->redirect(Yii::app()->user->returnUrl == '/' ? Yii::app()->user->getLink() : Yii::app()->user->returnUrl);
		}
  	$this->render('signin', array('model' => $model));
  }
  
  public function actionSignup()
  {
    $error = false;
    $email = null;
    if(isset($_POST['signup']) && isset($_POST['signup']['email']))
    {
      $email = trim($_POST['signup']['email']);
      $validator = new CEmailValidator;
      if($validator->validateValue($email))
      {
        if($user = User::createByEmail($email))
          $this->redirect(Yii::app()->user->returnUrl);
        else
          $error = Yii::t('security', 'User with this email is already registered');;
      }
      else
        $error = Yii::t('security', 'Invalid email format');
    }
    $this->pageTitle = Yii::t('app', 'Sign up');
  	$this->render('signup', array('error' => $error, 'email' => $email));
  }
  
  public function actionSignout()
	{
  	Yii::app()->user->logout();
  	$this->redirect(array('main/homepage'));
	}
	
	public function actionRestorePassword($user = null, $key = null)
	{
	  $this->layout = 'narrowWithPageHeader';
	  $this->pageTitle = Yii::t('security', 'Restore password');
	  if(!is_null($user) && !is_null($key))
	  {
  	  $user = User::retrieveByHash($user);
  	  if($user && $user->restorePasswordValid($key))
      {
        $user->resetPassword();
        if(Yii::app()->user->isGuest || Yii::app()->user->getId() != $user->getPrimaryKey())
          Yii::app()->user->loginAsUser($user);
        $this->redirect(array('account/changePassword'));
      }
      else
        $this->render('restorePasswordInvalid');
	  }
	  else
	  {
  	  $error = null;
  	  $login = null;
  	  if(isset($_POST['restorePassword']['login']))
  		{
  		  $login = trim($_POST['restorePassword']['login']);
  		  if(!$login)
  		    $error =  Yii::t('security', 'Enter your email or nickname');
  			elseif($user = User::retrieveByLogin($login))
  			{
  			  if($user->setRestorePasswordHash())
    			  $this->redirect(array('security/restorePasswordSended'));
          else
    			  $error = Yii::t('security', 'Unable to send link to password restore');
  			}
        else
          $error = Yii::t('security', 'User not found');
  		}
    	$this->render('restorePassword', array('error' => $error, 'login' => $login));
    }
	}
	
	public function actionRestorePasswordSended()
	{
	  $this->layout = 'narrowWithPageHeader';
	  $this->pageTitle = Yii::t('security', 'Restore password');
	  $this->render('restorePassword', array('sended' => 'yes'));
	}
	
	public function actionEndpoint()
	{
  	Hybrid_Endpoint::process();
	}
	
	public function actionAuth($provider)
	{
  	//
	}
}

protected/views/security/restorePassword.php
<?php if(isset($sended)):?>

<p class="lead text-success"><?php echo Yii::t('security', 'Email with instructions to reset your password sent to your email')?></p>

<?php else:?>

<form action="<?php echo $this->createUrl('security/restorePassword') ?>" method="post">
  <div class="form-group <?php if($error) echo 'has-error'?>">
    <input type="text" name="restorePassword[login]" placeholder="<?php echo Yii::t('security', 'Enter your email or nickname')?>" class="form-control" value="<?php if($login) echo CHtml::encode($login)?>">
    <p class="error help-block"><?php if($error) echo $error ?></p>
  </div>
  <div class="form-group text-center">
    <button type="submit" class="btn btn-success btn-lg"><?php echo Yii::t('app', 'Send')?></button>
  </div>
</form>

<?php endif ?>

protected/views/security/restorePasswordInvalid.php
<p class="lead text-danger"><?php echo Yii::t('security', 'Link to the password recovery is not valid')?></p>

protected/views/security/signin.php
<div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
  <div class="page-header">
    <h1><?php echo CHtml::encode($this->pageTitle) ?></h1>
  </div>
  <form action="<?php echo $this->createUrl('security/signin') ?>" method="post">
    <div class="form-group <?php if($model->hasErrors('login')) echo 'has-error'?>">
      <input type="text" name="singin[login]" placeholder="<?php echo $model->getAttributeLabel('login')?>" class="form-control" value="<?php echo $model->login?>">
      <p class="error help-block"><?php echo $model->getError('login')?></p>
    </div>
    <div class="form-group <?php if($model->hasErrors('password')) echo 'has-error'?>">
      <input type="password" name="singin[password]" class="form-control" placeholder="<?php echo $model->getAttributeLabel('password')?>">
      <p class="error help-block"><?php echo $model->getError('password')?></p>
    </div>
    <div class="form-group text-center">
      <button type="submit" class="btn btn-success btn-lg"><?php echo Yii::t('security', 'Sign in')?></button>
    </div>
  </form>
  
  <p class="text-center"><a href="<?php echo $this->createUrl('security/signup')?>"><?php echo Yii::t('security', 'New to Timerz?')?></a></p>
  <p class="text-center"><a href="<?php echo $this->createUrl('security/restorePassword')?>"><?php echo Yii::t('security', 'Forgot password?')?></a></p>
</div>

protected/views/security/signup.php
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="page-header text-center">
    <h1><?php echo CHtml::encode($this->pageTitle) ?></h1>
  </div>
  <form action="<?php echo $this->createUrl('security/signup') ?>" method="post">
    <div class="form-group <?php if($error) echo 'has-error'?>">
      <input type="text" name="signup[email]" placeholder="<?php echo Yii::t('security', 'Enter your email')?>" class="form-control text-center" value="<?php if(!is_null($email)) echo $email?>">
      <p class="error help-block text-center"><?php if($error) echo $error?></p>
    </div>
    <div class="form-group text-center">
      <button type="submit" class="btn btn-success btn-lg"><?php echo Yii::t('security', 'Continue')?></button>
    </div>
  </form>
  <p class="text-center"><a href="<?php echo $this->createUrl('security/signin')?>"><?php echo Yii::t('security', 'Already have account?')?></a></p>
</div>